{
 "title": "PXF Service Dashboard",
 "tags": [ "pxf" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(system_cpu_usage, application)"
    }
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": {
     "query": "label_values(pxf_operation_seconds_active_count{application=~\"$application\"}, profile)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(system_cpu_usage{application=~\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PXF Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PXF Instances Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"pxf-service\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "☕ JVM Heap Usage by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{application=~\"$application\", area=\"heap\", instance=~\"$instance\"}) / sum by (instance) (jvm_memory_max_bytes{job=\"pxf-service\", area=\"heap\", instance=~\"$instance\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PXF Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Active Read Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pxf_operation_seconds_active_count{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\", operation=\"read\"})",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "Active Write Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pxf_operation_seconds_active_count{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\", operation=\"write\"})",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Active Operations Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation, profile, datasource) (pxf_operation_seconds_active_count{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"})",
     "legendFormat": "{{operation}} / {{profile}} /{{datasource}}"
    }
   ]
  },
  {
   "title": "Active Operations Duration (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (operation, profile, datasource, instance) (pxf_operation_seconds_max{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"})",
     "legendFormat": "{{operation}} / {{profile}} / {{datasource}} / {{instance}} "
    }
   ]
  },
  { "title": "PXF Executor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "PXF Executor Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pxf_executor_active_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(pxf_executor_pool_max_threads{job=\"pxf-service\", instance=~\"$instance\"})",
     "legendFormat": "Max number of threads"
    }
   ]
  },
  {
   "title": "PXF Executor Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pxf_executor_queued_tasks{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(pxf_executor_queue_capacity_tasks{application=~\"$application\", instance=~\"$instance\"})",
     "legendFormat": "Max number of tasks in queue"
    }
   ]
  },
  {
   "title": "Fragment Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fragment Processing Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (profile, datasource) (pxf_fragments_sent_seconds_active_count{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"})",
       "legendFormat": "{{profile}} / {{datasource}}"
      }
     ]
    },
    {
     "title": "Fragment Processing Duration (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (profile, datasource) (pxf_fragments_sent_seconds_max{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"})",
       "legendFormat": "{{profile}}/{{datasource}}"
      }
     ]
    },
    {
     "title": "Fragmenter & Bridge Call Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (profile, instance, outcome) (increase(pxf_fragmenter_call_seconds_count{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "fragmenter call {{outcome}} - {{profile}}/{{instance}}"
      },
      {
       "expr": "sum by (profile, instance, outcome) (increase(pxf_bridge_begin_seconds_count{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "bridge call {{outcome}} - {{profile}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Bridge Begin Duration (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (operation, profile, datasource) (pxf_bridge_begin_seconds_max{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"})",
       "legendFormat": "{{operation}}/ {{profile}} / {{datasource}}"
      }
     ]
    },
    {
     "title": "Fragmenter Call Duration (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (operation, profile, datasource) (pxf_fragmenter_call_seconds_max{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"})",
       "legendFormat": "{{operation}}/{{profile}}/{{datasource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Records & Bytes Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Records Read Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (profile, datasource, instance) (rate(pxf_records_sent_total{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{profile}} / {{datasource}} / {{instance}}"
      }
     ]
    },
    {
     "title": "Records Written Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (profile, datasource, instance) (rate(pxf_records_received_total{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{profile}} / {{datasource}}/  {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes Read Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (profile, datasource, instance) (rate(pxf_bytes_sent_total{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{profile}} / {{datasource}}/ {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes Written Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (profile, datasource, instance) (rate(pxf_bytes_received_total{application=~\"$application\", profile=~\"$profile\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{profile}} / {{datasource}} / {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "HTTP Error Rate (5xx)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (uri, method, status) (rate(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", status=~\"5..\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{uri}} {{status}}"
      }
     ]
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "busy - {{instance}}"
    },
    {
     "expr": "tomcat_threads_current_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "current - {{instance}}"
    },
    {
     "expr": "tomcat_threads_config_max_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "max - {{instance}}"
    }
   ]
  },
  {
   "title": "Thread Pool Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{application=~\"$application\", instance=~\"$instance\"} / tomcat_threads_config_max_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tomcat Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "current - {{instance}}"
    },
    {
     "expr": "tomcat_connections_config_max_connections{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "max - {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\", area=\"heap\"})",
       "legendFormat": "used - {{instance}}"
      },
      {
       "expr": "sum by (instance) (jvm_memory_max_bytes{application=~\"$application\", instance=~\"$instance\", area=\"heap\"})",
       "legendFormat": "max - {{instance}}"
      }
     ]
    },
    {
     "title": "JVM Non-Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used - {{instance}}"
      },
      {
       "expr": "sum by (instance) (jvm_memory_committed_bytes{application=~\"$application\", instance=~\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pause Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (gc, instance) (rate(jvm_gc_pause_seconds_count{application=~\"$application\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{gc}} - {{instance}}"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{application=~\"$application\", instance=~\"$instance\"}",
       "legendFormat": "live - {{instance}}"
      },
      {
       "expr": "jvm_threads_daemon_threads{application=~\"$application\", instance=~\"$instance\"}",
       "legendFormat": "daemon - {{instance}}"
      },
      {
       "expr": "jvm_threads_states_threads{application=~\"$application\", instance=~\"$instance\", state=\"blocked\"}",
       "legendFormat": "blocked - {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{application=~\"$application\", instance=~\"$instance\"}",
       "legendFormat": "process - {{instance}}"
      },
      {
       "expr": "system_cpu_usage{application=~\"$application\", instance=~\"$instance\"}",
       "legendFormat": "system - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}