; Local integration test configuration
; Suffix-part of section name treated as test GROUP
; Example: `[test.smoke]` is `smoke` test

; For USE_FDW and USE_SSL: any non-empty value is treated as enabled (true)
; except the literal string "false", which is treated as disabled

; For PROFILE: absent `profile` param will be treated as `all`

[general]
; Variables are case-sensitive!
GGDB_IMAGE=ghcr.io/greengagedb/greengage/ggdb6_ubuntu:latest
IT_IMAGE=greengagedb/ggdb6_pxf_automation
IT_TAG=it
DEBUG_DIR=artifacts/docker_logs
DEBUG=true

[test.smoke]
profile=smoke

[test.gpdb]
profile=gpdb

[test.jdbc]
profile=jdbc

[test.smoke]
profile=smoke
fdw=1

[test.gpdb]
profile=gpdb
fdw=1

[test.jdbc]
profile=jdbc
fdw=1

[test.ggdbssl]
profile=ggdbssl
fdw=1
ssl=1
