[general]
# Docker images for integration tests
ggdb_image = ghcr.io/greengagedb/greengage/ggdb6_ubuntu:latest
it_image = greengedb/ggdb6_pxf_automation
it_tag = it

# Debug settings
debug_dir = artifacts/docker_logs
debug = true

[tests.smoke]
fdw = false
ssl = false
profile = smoke

[tests.gpdb]
fdw = false
ssl = false
profile = gpdb

[tests.jdbc]
fdw = false
ssl = false
profile = jdbc

[tests.smoke_fdw]
fdw = true
ssl = false
profile = smoke

[tests.gpdb_fdw]
fdw = true
ssl = false
profile = gpdb

[tests.jdbc_fdw]
fdw = true
ssl = false
profile = jdbc

[tests.ggdbssl]
fdw = true
ssl = true
profile = ggdbssl
