# .github/workflows/greengage-compat.yml
name: Greengage compatible tests

# Runs automatically on pull requests if TAG and VERSION is defined
env:
  TAG: 'GG-246'
  VERSION: '6'

on:
  pull_request:
    branches: ['**'] # Trigger on pull requests for all branches

# Concurrency control to cancel previous runs on new push to same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number }}
  cancel-in-progress: true  # Automatically cancel any previous runs for the same group

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      enabled: ${{ steps.check.outputs.enabled }}
    steps:
      - id: check
        run: |
          echo ">>> DEBUG <<<"
          echo ">>> TAG=$TAG"
          echo ">>> VERSION=$VERSION"
          [[ -n "$TAG" && -n "$VERSION" ]] && enabled='true' ||  enabled='false'
          echo "enabled=$enabled" >> $GITHUB_OUTPUT
  regression:
    needs: check
    if: needs.check.outputs.enabled == 'true'
    name: Regression on ggdb${VERSION}_ubuntu:${TAG}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
      - name: Build PXF regression compatible tests image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ci/Dockerfile.${{ github.job }}
          push: false
          tags: greengagedb/ggdb${VERSION}_pxf_regression:${TAG}
          build-args: GGDB_IMAGE=ghcr.io/greengagedb/greengage/ggdb${VERSION}_ubuntu:${TAG}

      - name: Run regression on greengagedb/ggdb${VERSION}_pxf_regression:${TAG}
        shell: bash
        run: |
          mkdir logs
          docker run --user root:root \
            -v ./logs:/logs \
            --sysctl 'kernel.sem=500 1024000 200 4096' \
            --privileged \
            greengagedb/ggdb${VERSION}_pxf_regression:${TAG} \
            bash -c "
              set +e
              cd /tmp/build || status=1
              pxf_src/ci/test_in_docker.sh
              status=\$?
              find /tmp/build/pxf_src/fdw -type f -name *.diffs -exec mv -f {} /logs \;
              echo \">>> STATUS \$status\"
              exit \${status:-1}
            "

      - name: Upload regression artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-ggdb${VERSION}-${TAG}
          path: logs
          retention-days: 7
          if-no-files-found: warn

  integration:
    needs: check
    if: needs.check.outputs.enabled == 'true'
    name: Integration on ggdb${VERSION}_ubuntu:${TAG}
    uses: ./.github/workflows/integration-tests.yml
    with:
      image: ghcr.io/greengagedb/greengage/ggdb${VERSION}_ubuntu:${TAG}
      version: ${VERSION}
      release: compat
      tests_matrix: |
        [
          { "test": "smoke" },
          { "test": "gpdb" },
          { "test": "jdbc" },
          { "test": "smoke", "fdw": "true" },
          { "test": "gpdb", "fdw": "true" },
          { "test": "jdbc", "fdw": "true" },
          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
        ]
