# .github/workflows/greengage-ci.yml
name: Greengage PXF CI

on:
  push:
    branches: ['main']  # Trigger on push to main (after merged PR)
    tags: ['**']   # Trigger on tags for versioned releases
  pull_request:
    branches: ['**'] # Trigger on pull requests for all branches

# Concurrency control to cancel previous runs on new push to same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: true  # Automatically cancel any previous runs for the same group

env:
  GREENGAGE: |
    [
      { "version": "6", "image": "greengagedb/ggdb", "tag": "6.30.1"  },
      { "version": "7", "image": "greengagedb/ggdb", "tag": "7.4.0"   },
      { "version": "6", "image": "ghcr.io/greengagedb/greengage/ggdb", "tag": "GG-246" },
      { "version": "7", "image": "ghcr.io/greengagedb/greengage/ggdb", "tag": "latest" }
    ]

jobs:
  generate-matrix:
    name: Generate Greengage Images matrix
    runs-on: ubuntu-24.04
    outputs:
      greengage_matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix from env
        id: set-matrix
        run: |
          cat > /tmp/matrix.json << 'JSON_END'
          ${{ env.GREENGAGE }}
          JSON_END
          COMPRESSED=$(jq -c . /tmp/matrix.json)
          echo "matrix=$COMPRESSED" >> $GITHUB_OUTPUT

  build:
    needs: generate-matrix
    name: Build DEB package
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build/deb
        with:
          image:   ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].image }}
          version: ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].version }}
          tag:     ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].tag }}

  regression:
    needs: generate-matrix
    name: Regression on ggdb${{ matrix.version }}:${{ matrix.tag || 'latest' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests/regression
        with:
          image:   ${{ matrix.image }}
          version: ${{ matrix.version }}
          tag:     ${{ matrix.tag || 'latest' }}

  integration-ggdb6-stable:
    needs: generate-matrix
    name: Integration on ggdb${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].version }}:${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].tag }}
    uses: ./.github/workflows/greengage-reusable-tests-integration.yml
    with:
      image:   ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].image }}
      version: ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].version }}
      tag:     ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].tag }}
      tests_matrix: |
        [
          { "test": "smoke" },
          { "test": "gpdb" },
          { "test": "jdbc" },
          { "test": "smoke", "fdw": "true" },
          { "test": "gpdb", "fdw": "true" },
          { "test": "jdbc", "fdw": "true" },
          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
        ]

  integration-ggdb6-devel:
    needs: generate-matrix
    name: Integration on ggdb${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].version }}:${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].tag }}
    uses: ./.github/workflows/greengage-reusable-tests-integration.yml
    with:
      image:   ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[1].image }}
      version: ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[1].version }}
      tag:     ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[1].tag }}
      tests_matrix: |
        [
          { "test": "smoke" },
          { "test": "gpdb" },
          { "test": "jdbc" },
          { "test": "smoke", "fdw": "true" },
          { "test": "gpdb", "fdw": "true" },
          { "test": "jdbc", "fdw": "true" },
          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
        ]

  integration-ggdb7-stable:
    needs: generate-matrix
    name: Integration on ggdb${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].version }}:${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].tag }}
    uses: ./.github/workflows/greengage-reusable-tests-integration.yml
    with:
      image:   ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[2].image }}
      version: ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[2].version }}
      tag:     ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[2].tag }}
      tests_matrix: |
        [
          { "test": "smoke" },
          { "test": "gpdb" },
          { "test": "jdbc" },
          { "test": "smoke", "fdw": "true" },
          { "test": "gpdb", "fdw": "true" },
          { "test": "jdbc", "fdw": "true" },
          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
        ]

  integration-ggdb7-devel:
    needs: generate-matrix
    name: Integration on ggdb${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].version }}:${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[0].tag }}
    uses: ./.github/workflows/greengage-reusable-tests-integration.yml
    with:
      image:   ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[3].image }}
      version: ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[3].version }}
      tag:     ${{ fromJson(needs.generate-matrix.outputs.greengage_matrix)[3].tag }}
      tests_matrix: |
        [
          { "test": "smoke" },
          { "test": "gpdb" },
          { "test": "jdbc" },
          { "test": "smoke", "fdw": "true" },
          { "test": "gpdb", "fdw": "true" },
          { "test": "jdbc", "fdw": "true" },
          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
        ]
