# .github/workflows/greengage-compat.yml
name: Greengage compatible tests

# Runs automatically on pull requests if both GG_BRANCH and GG_VERSION are set.
# To disable automatic testing, set either GG_BRANCH or GG_VERSION to empty string.
env:
  GG_BRANCH: ''
  GG_VERSION: '6'

on:
  pull_request:
    branches: ['**'] # Trigger on pull requests for all branches

# Concurrency control to cancel previous runs on new push to same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number }}
  cancel-in-progress: true  # Automatically cancel any previous runs for the same group

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.check.outputs.TAG }}
      VERSION: ${{ steps.check.outputs.VERSION }}
      enabled: ${{ steps.check.outputs.enabled }}
    steps:
      - name: Check mode and setup environment
        id: check
        run: |
          echo ">>> DEBUG <<<"
          echo ">>> TAG=$GG_BRANCH"
          echo ">>> VERSION=$GG_VERSION"
          echo "TAG=$GG_BRANCH" >> $GITHUB_OUTPUT
          echo "VERSION=$GG_VERSION" >> $GITHUB_OUTPUT
          if [[ -n "$GG_BRANCH" && -n "$GG_VERSION" ]]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi

  regression:
    needs: setup
    if: needs.setup.outputs.enabled == 'true'
    name: Regression on ggdb${{ needs.setup.outputs.VERSION }}_ubuntu:${{ needs.setup.outputs.TAG }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
      - name: Build PXF regression compatible tests image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ci/Dockerfile.${{ github.job }}
          push: false
          tags: greengagedb/ggdb${{ needs.setup.outputs.VERSION }}_pxf_regression:${{ needs.setup.outputs.TAG }}
          build-args: GGDB_IMAGE=ghcr.io/greengagedb/greengage/ggdb${{ needs.setup.outputs.VERSION }}_ubuntu:${{ needs.setup.outputs.TAG }}

      - name: Run regression on greengagedb/ggdb${{ needs.setup.outputs.VERSION }}_pxf_regression:${{ needs.setup.outputs.TAG }}
        shell: bash
        run: |
          mkdir logs
          docker run --user root:root \
            -v ./logs:/logs \
            --sysctl 'kernel.sem=500 1024000 200 4096' \
            --privileged \
            greengagedb/ggdb${{ needs.setup.outputs.VERSION }}_pxf_regression:${{ needs.setup.outputs.TAG }} \
            bash -c "
              set +e
              cd /tmp/build || status=1
              pxf_src/ci/test_in_docker.sh
              status=\$?
              find /tmp/build/pxf_src/fdw -type f -name *.diffs -exec mv -f {} /logs \;
              echo \">>> STATUS \$status\"
              exit \${status:-1}
            "

      - name: Upload regression artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-ggdb${{ needs.setup.outputs.VERSION }}-${{ needs.setup.outputs.TAG }}
          path: logs
          retention-days: 7
          if-no-files-found: warn

  integration:
    needs: setup
    if: needs.setup.outputs.enabled == 'true'
    name: Integration on ggdb${{ needs.setup.outputs.VERSION }}_ubuntu:${{ needs.setup.outputs.TAG }}
    uses: ./.github/workflows/integration-tests.yml
    with:
      image: ghcr.io/greengagedb/greengage/ggdb${{ needs.setup.outputs.VERSION }}_ubuntu:${{ needs.setup.outputs.TAG }}
      version: ${{ needs.setup.outputs.VERSION }}
      release: compat
      tests_matrix: |
        [
          { "test": "smoke" },
          { "test": "gpdb" },
          { "test": "jdbc" },
          { "test": "smoke", "fdw": "true" },
          { "test": "gpdb", "fdw": "true" },
          { "test": "jdbc", "fdw": "true" },
          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
        ]
